import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navItems = [
  { label: "home", href: "/" },
  { label: "about", href: "/about" },
  { label: "content", href: "/content" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={cn(inter.className, "min-h-dvh")}
        style={{ background: `#F2F2F2` }}
      >
        <header
          className="container h-16 flex items-center border-b justify-between"
          style={{ background: `#FFF` }}
        >
          <h1 className="font-bold">next-test-app</h1>
          <ul className="flex gap-4">
            {navItems.map((item) => (
              <li key={item.label}>
                <button>
                  <Link href={item.href}>{item.label}</Link>
                </button>
              </li>
            ))}
          </ul>
        </header>
        {children}
        <footer className="container sticky top-full h-16 flex items-center border-t">
          <p>next-test-app</p>
        </footer>
      </body>
    </html>
  );
}
