import Head from "next/head";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const navItems = [
  { label: "home", href: "/" },
  { label: "about", href: "/about" },
  { label: "content", href: "/content" },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <Head>
        <title>Next.js Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body className={inter.className}>
        <header className="header">
          <h1 className="font-bold">my-history</h1>
          <ul className="nav">
            {navItems.map((item) => (
              <li key={item.label}>
                <button>
                  <Link href={item.href}>{item.label}</Link>
                </button>
              </li>
            ))}
          </ul>
        </header>
        {children}
        <footer className="footer">
          <p>my-app</p>
        </footer>
      </body>
    </html>
  );
}
