import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nextjs Project",
  description: "Generated by create next app",
};

const navItems = [
  { label: "home", href: "/" },
  { label: "about", href: "/about" },
  { label: "content", href: "/content" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="header">
          <h1 className="font-bold">my-history</h1>
          <ul className="nav">
            {navItems.map((item) => (
              <li key={item.label}>
                <button>
                  <Link href={item.href}>{item.label}</Link>
                </button>
              </li>
            ))}
          </ul>
        </header>
        {children}
        <footer className="footer">
          <p>my-app</p>
        </footer>
      </body>
    </html>
  );
}
